"""
Formats structured clinical JSON into a safe, grounded OPD note using Ollama.

Design principles:
- LLM is ONLY used for narrative text (Chief Complaint, HPI, Assessment)
- Medications and Advice are NEVER generated by the LLM
- No hallucinated investigations, plans, or reasoning possible
"""

import json
import requests
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)

MODEL_NAME = "gemma3:1b"
OLLAMA_TIMEOUT_SECONDS = 30
OLLAMA_API_URL = "http://localhost:11434/api/generate"
MAX_JSON_SIZE_BYTES = 50000

SYSTEM_PROMPT = """
You are a medical scribe. Generate ONLY a factual clinical note from the JSON provided.

STRICT RULES:
1. Use ONLY symptoms listed in the "symptoms" field. Do NOT add any symptoms not explicitly listed.
2. Do NOT add "Interpretation", "Impression", or reasoning sections.
3. Do NOT use words like: possibly, likely, suggests, warrants, appears, consistent with, may indicate.
4. If a symptom is in Hindi, translate it directly (e.g., "बुखार" → "fever", "कमजोरी" → "weakness").
5. Do NOT invent, expand, or infer any medical information.
6. If duration or location is present in symptom object, include it exactly as written.

OUTPUT FORMAT (omit empty sections):
Chief Complaint: Patient is expierencing .....[exact value from chief_complaint field]
History of Present Illness: Patient exhibits ....[List ONLY symptoms from "symptoms" array, with duration/location if present]
Negative Findings: Patient does not exhibit .... [List ONLY items from "negatives" array]
Assessment: Assessment concludes that the patient has ......[Exact text from "diagnosis" array, no additions]

CRITICAL: Do NOT output sections for medications or advice - they are added separately.
DO not add unneeded medical reasoning
"""

# Forbidden phrases that indicate LLM hallucination/reasoning
FORBIDDEN_PHRASES = [
    "possibly", "likely", "suggests", "warrants", "consistent with", 
    "appears to", "may indicate", "interpretation:", "impression:",
    "requires further", "should be evaluated", "viral illness",
    "bacterial infection", "differential diagnosis"
]

def validate_input(structured_json: Dict[str, Any]) -> None:
    """Validate input JSON structure and size."""
    if not isinstance(structured_json, dict):
        raise ValueError("Input must be a dictionary")
    json_str = json.dumps(structured_json, ensure_ascii=False)
    size = len(json_str.encode("utf-8"))
    if size > MAX_JSON_SIZE_BYTES:
        raise ValueError("Input JSON too large")

def call_ollama(prompt: str) -> str:
    """
    Call Ollama via HTTP API for stateless, single-shot inference.
    Each call gets a fresh context window (no history bleeding).
    """
    try:
        response = requests.post(
            OLLAMA_API_URL,
            json={
                "model": MODEL_NAME,
                "prompt": prompt,
                "stream": False,
                "options": {
                    "num_ctx": 2048,  # Fresh context each time
                    "temperature": 0.1,  # Low temperature for factual output
                    "top_p": 0.9,  # Reduce randomness
                }
            },
            timeout=OLLAMA_TIMEOUT_SECONDS
        )
        response.raise_for_status()

        result = response.json()
        return result.get("response", "").strip()

    except requests.exceptions.ConnectionError:
        raise RuntimeError("Cannot connect to Ollama. Is it running? (ollama serve)")
    except requests.exceptions.Timeout:
        raise RuntimeError("Ollama request timed out")
    except requests.exceptions.RequestException as e:
        raise RuntimeError(f"Ollama API error: {e}")
    except (KeyError, ValueError) as e:
        raise RuntimeError(f"Invalid Ollama response format: {e}")

def validate_llm_output(narrative: str) -> tuple[str, list[str]]:
    """
    Validate LLM output doesn't contain forbidden reasoning phrases.
    Returns: (narrative, list of warnings)
    """
    warnings = []
    narrative_lower = narrative.lower()

    for phrase in FORBIDDEN_PHRASES:
        if phrase.lower() in narrative_lower:
            warnings.append(f"LLM output contains forbidden phrase: '{phrase}'")
            logger.warning(f"Hallucination detected: {phrase}")

    return narrative, warnings

def generate_opd_note(structured_json: Dict[str, Any]) -> str:
    """
    Generate a safe OPD note from structured clinical JSON.

    LLM generates:
    - Chief Complaint
    - History of Present Illness
    - Negative Findings
    - Assessment

    System appends (deterministic):
    - Current Medications
    - Plan (Advice)
    """
    validate_input(structured_json)

    # Check if there's any clinical data
    has_symptoms = bool(structured_json.get("symptoms"))
    has_diagnosis = bool(structured_json.get("diagnosis"))
    has_meds = bool(structured_json.get("medications"))
    has_advice = bool(structured_json.get("advice"))

    if not (has_symptoms or has_diagnosis or has_meds or has_advice):
        return "No clinical data recorded in this session."

    json_str = json.dumps(structured_json, ensure_ascii=False, indent=2)

    prompt = f"""{SYSTEM_PROMPT}

INPUT JSON:
{json_str}

INSTRUCTIONS:
- Generate ONLY the sections listed in the OUTPUT FORMAT.
- Use ONLY data from the JSON above.
- Do NOT generate medications or advice sections.
- Do NOT add unneeded medical reasoning.
- Explain within limits what each thing means.
"""

    try:
        narrative = call_ollama(prompt).rstrip()

        # Validate output for hallucinations
        narrative, warnings = validate_llm_output(narrative)

        if warnings:
            logger.warning(f"LLM output validation warnings: {warnings}")
            # Use fallback if too many hallucinations detected
            if len(warnings) >= 2:
                logger.error("Multiple hallucinations detected, using fallback")
                narrative = generate_fallback_note(structured_json)

    except RuntimeError as e:
        # Log error but return a fallback note instead of crashing
        logger.error(f"Ollama generation failed: {e}")
        narrative = generate_fallback_note(structured_json)

    lines = [narrative]

    # Append medications deterministically
    medications = structured_json.get("medications") or []
    if medications:
        lines.append("\nCurrent Medications:")
        for med in medications:
            lines.append(f"- {med}")

    # Append advice deterministically
    advice = structured_json.get("advice") or []
    if advice:
        lines.append("\nPlan:")
        for item in advice:
            lines.append(f"- {item}")

    return "\n".join(lines)

def generate_fallback_note(structured_json: Dict[str, Any]) -> str:
    """
    Generate a simple note without LLM if Ollama fails.
    Useful for demos when Ollama is down or produces poor output.
    """
    lines = []

    # Patient info
    name = structured_json.get("patient_name")
    age = structured_json.get("patient_age")
    if name or age:
        info_parts = []
        if name:
            info_parts.append(f"Name: {name}")
        if age:
            info_parts.append(f"Age: {age}")
        lines.append(" | ".join(info_parts))
        lines.append("")

    # Chief Complaint
    cc = structured_json.get("chief_complaint")
    if cc:
        lines.append(f"Chief Complaint: {cc}")

    # Symptoms
    symptoms = structured_json.get("symptoms", [])
    if symptoms:
        lines.append("\nHistory of Present Illness:")
        for s in symptoms:
            name = s.get("name", "")
            duration = s.get("duration", "")
            location = s.get("location", "")
            detail = f"{name}"
            if location:
                detail += f" ({location})"
            if duration:
                detail += f" for {duration}"
            lines.append(f"- {detail}")

    # Negatives
    negatives = structured_json.get("negatives", [])
    if negatives:
        lines.append("\nNegative Findings:")
        lines.append(f"- Denies: {', '.join(negatives)}")

    # Diagnosis
    diagnosis = structured_json.get("diagnosis", [])
    if diagnosis:
        lines.append("\nAssessment:")
        for d in diagnosis:
            lines.append(f"- {d}")

    return "\n".join(lines)
